gui for detailed view and booking
lukasbals/itb5-culture-tickets-client pull request #5
Opened 2019-11-05 17:51 UTC by durigvanessa

created gui for detailed view and one for booking view
temporary version for testing

2019-11-05 20:03 UTC, lukasbals requested changes
Bitte die Controller noch testen ... sorry aber muss sein ...

2019-11-06 07:02 UTC, lukasbals approved these changes
Testen isch iwie fast unmögloch vei deana controller. Also lommas mol vorläufig weg 😅

2019-11-06 07:31 UTC, merged

2019-11-06 07:38 UTC, BakaBoing requested changes
alles in allem gut gemacht, allerdings funktionieren Felder teilweise noch nicht

2019-11-06 07:38 UTC, BakaBoing commented on src/main/java/at/fhv/td/gui/DetailedViewGuiController.java
> +        Float lowestPrice = _event.getPrices()[0];
da gibt es im eventDTO schon ein getter für: getMinPrice

2019-11-06 07:38 UTC, BakaBoing commented on src/main/resources/fxml_files/detailedView.fxml
> +    <Label GridPane.columnIndex="1" GridPane.rowIndex="4" fx:id="eventlocation"/>
dieser text wird wahrscheinlich abgeschnitten, bitte prüfen ob das bei anderen auch passiert

2019-11-06 07:38 UTC, BakaBoing commented on src/main/resources/fxml_files/eventBookingView.fxml
> +    <ComboBox GridPane.columnIndex="1" GridPane.rowIndex="4" fx:id="categoryname" prefWidth="140"/>
bei der Auswahl der Kategorie ändert sich der Preis nicht, bzw. er wird gar nie angezeigt

2019-11-06 07:38 UTC, BakaBoing commented on src/main/resources/fxml_files/eventBookingView.fxml
> +    <ComboBox GridPane.columnIndex="1" GridPane.rowIndex="6" fx:id="ticketnumber" prefWidth="140"/>
für was ist dieses Feld?